version: '2'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/var/lib/mongodb
    restart: always
  deployd:
    image: japanvik/deployd
    ports: 
      - "2403:2403"
    restart: always
    depends_on:
      - mongo